### ISSUE TITLE
Multi-head attention transformer usage

### ISSUE THREAD

**Issue by shirin1996** [EhsanMashhadi/PredictPy#7]
The variation of the price trend of cryptocurrencies especially the altcoins could be captured using the multi-head attention mechanism implemented in a transformer, where the attention heads attend to the tokens that are relevant to each current token based on varying short-term and long-term dependencies. Therefore, you can apply a multi-head attention-based transformer encoder-decoder model ion the hourly data of your target coin price for its prediction over time.

**Comment by shirin1996** [comment]
Yes! Sure! Since my project is also a transformer-based model and I have hands-on knowledge of this architecture! With that in mind, I am going to use the same idea and contribute to your project via PR. @EhsanMashhadi

**Comment by EhsanMashhadi** [comment]
@shirin1996 I think the code for adding this feature has been merged in PR #11 , so I close this issue.
